### ISSUE TITLE
olubalance 1.2 planned updates

### ISSUE THREAD

**Issue by odinsride** [odinsride/olubalance#34]
**olubalance 1.2 will mark the final feature release of the Rails based front-end. Going forward, olubalance will be split into a Rails API and a Vue frontend.  The following features are planned for 1.2**

- [x] Deleting an account will no longer permenantly delete the account from the database, though it will be hidden from the user. An admin can easily recover accidentally deleted accounts and transactions this way.
- [x] A new feature will be added to inactivate accounts and show them in a separate area of olubalance. This can be helpful for record keeping.
- [x] Transaction search will be added (#21)
- [x] Accounts will have a field to store the last 4 digits of the account number for ease of identifying accounts
- [x] Attachments will be available at the account level for storing statements (#14)
- [x] Image and attachment uploads will be renamed per the transaction/account details
- [ ] ~~A new account type will be added for Credit Cards which will allow for separation and alternate display properties on the accounts screen (#13)~~
- [x] Transactions will have autocomplete enabled for the description field (#8)
- [x] Bugfix for account deletion
- [ ] ~~Pagination options to be added for viewing more transactions at a time~~
- [x] Bugfix for going back to the page you were on after updating a transaction several pages back
